export { default as HomeSection } from './Home'
export { default as AboutSection } from './About'
export { default as PopularSection } from './Popular'
export { default as FeaturesSection } from './Features'
export { default as FeaturedSection } from './Featured'
export { default as OfferSection } from './Offer'
export { default as LogosSection } from './Logos'